#!/bin/sh

#
# net.eth0, net.eth1, network, wicd, NetworkManager
service="net.eth0"

if [ $(rc-service -e net.eth0) ]
then
	service="net.eth0"
else
	service="network"
fi

case "$1" in
	suspend-vm)
		rc-service $service stop
		;;
	resume-vm)
		rc-service $service start
		;;
	*)
		;;
esac

